spring.datasource.url=jdbc:postgresql://dpg-d8241pvavr4c739f0da0-a.frankfurt-postgres.render.com:5432/fitnesstrainer
spring.datasource.username=fitnessuser
spring.datasource.password=TM1B48WoeOxX8D2BwnKjMGB9xXCSC5lF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}